### ISSUE TITLE
OS Packager: No CSV upload via Safari

### ISSUE THREAD

**Issue by DianaMPG** [openspending/openspending#1100] opened 2016-09-14 14:09 UTC
CSV upload option is not available when OS packager is opened via Safari

**Comment by kravets-levko** [comment] 2016-12-05 12:25
@DianaMPG can you please provide a bit more info? Screenshots, maybe messages from console, etc. - everything will be useful.
P.S. I don't have access to any device with Safari at the moment, will find some and try to reproduce this bug.

**Comment by DianaMPG** [comment] 2016-12-05 12:28
@kravets-levko I will try to reproduce the bug, thanks.

**Comment by cecilaki** [comment] 2016-12-08 01:43
Guys. I've just reproduced it. Well basically nothing happens when you upload a file on the first step of the packager. You don't see it being processed as it is on Chrome. And no error message either.

**Comment by pwalsh** [comment] 2016-12-08 06:16
I *can* upload files on Safari, using the file upload and ingest URL methods.

I'm on Safari 10.0.1 with macOS 10.12.1

**Comment by akariv** [comment] 2016-12-08 06:38
@cecilaki can you give more details on what exactly didn't work:
- The file you tried to upload
- By which method (URL/file upload)
- Safari version and OS version

Perhaps the problem is that error conditions are not displayed correctly (e.g. if the validation fails, file cannot be fetched etc.)

**Comment by cecilaki** [comment] 2016-12-08 09:35
I'm on Safari 9.0.3 with MacOS 10.11.3
Tried to upload with file upload (didn't try URL but can if needed) 
And here's the file >
[FrenchState_Spendings_1995_2015.csv.zip](https://github.com/openspending/openspending/files/639000/FrenchState_Spendings_1995_2015.csv.zip)

**Comment by akariv** [comment] 2016-12-08 09:51
@cecilaki did you upload the zip file or the inside it?

**Comment by cecilaki** [comment] 2016-12-08 10:16
The inside!:)

**Comment by pwalsh** [comment] 2017-06-02 10:02
@akariv can someone look at this soon

**Comment by akariv** [comment] 2017-06-05 12:05
Just tried to upload the file in Safari without issue.
I guess that this was resolved along the way or a local issue(?)

closing for now.

**Closed by akariv** 2017-06-05 12:05 UTC
Labels: bug, Packager, prioritized
