### ISSUE TITLE
New themes for OS-Viewer requires restart

### ISSUE THREAD

**Issue by mlukasch** [openspending/openspending#1227] opened 2017-03-14 15:06 UTC
Hello @akariv,
we were trying out the microsite on the FHG-Server @pierorex is currently working on.
Via the Microsite-App users can create new themes which will be stored in json-format similar to those ones here:
https://github.com/openspending/os-viewer/tree/master/app/config/themes
But in order for the OS-Viewer to recognize the created theming-json-files a restart of the OS-Viewer-app (hosted on the Fhg-Server) is currently necessary. So @pierorex and me wanted to ask, if it would be possible to add some kind of reload mechanism to OS-Viewer in order to detect new theming-json-files without the need to restart the OS-Viewer-app.

Thank you.

**Comment by akariv** [comment] 2017-03-14 15:28
Yes, I think that if you use a component such as https://github.com/mikeal/watch it should be possible.

**Comment by pierorex** [comment] 2017-03-14 15:32
@akariv is there an administration command we can use to tell os-viewer to reload its theme files without restarting it?

**Comment by akariv** [comment] 2017-03-14 15:33
not at the moment

**Comment by pierorex** [comment] 2017-03-14 15:37
I see, thank you :)

**Comment by pwalsh** [comment] 2017-06-05 12:08
Seeing as this is by design, closing issue.

**Closed by pwalsh** 2017-06-05 12:08 UTC
