### ISSUE TITLE
Packager: Upload progress not shown

### ISSUE THREAD

**Issue by michaeljokf** [openspending/openspending#1372] opened 2018-06-29 12:55 UTC
Hello,

the upload progress is not shown in step 4 of the packager. See screenshot. In the inspect-mode it looks like data is still being uploaded. After Brook mentioned it, I checked the admin page and saw that the file actually uploaded. File also attached. 
This is really bad for the users, because it does not give any feedback on successful upload and does not show the progress. Maybe you guys can look into it eventually?
Happy that the upload actually still works! :+1: 

Dataset was this one: https://openspending.org/viewer/a6a16b964a7e784f99adecc47f26318a:cologne-test18?lang=en

![bildschirmfoto von 2018-06-25 18-46-46](https://user-images.githubusercontent.com/22743376/42093367-5feb5a98-7bac-11e8-968d-d2f4ba225397.png)

**Comment by brew** [comment] 2018-06-29 13:01
Thanks for the report and details. Very useful and we'll definitely be looking at this soon. Closing this as a duplicate of #1367.

**Closed by brew** 2018-06-29 13:01 UTC
