### ISSUE TITLE
Get rid of dataset titles in favour of richer metadata

### ISSUE THREAD

**Issue by pudo** [openspending/openspending#834] opened 2014-12-21 23:12 UTC
This is a bit crazy, but I think part of the difficulty of navigating OpenSpending right now is that we're asking people to name things which don't really have a name. Instead, we should be getting them to describe the dataset in much more detail, including details such as these: 

* What is the name of the administrative body to which it applies? 
* What is the level of government that this applies to? 
* What stage in the budget cycle does this dataset most represent?
* What is the name of the political body which decided it?
* Where was it initially published on the web? 
* When was it initially published? 
* What is the temporary extent and granularity of the data?

**Comment by pudo** [comment] 2015-01-03 16:34
dupe of #581

**Comment by rgrp** [comment] 2015-04-26 18:04
DUPLICATE of #581.

**Closed by rgrp** 2015-04-26 18:04 UTC
