### ISSUE TITLE
OS Viewer: too many items on particular views

### ISSUE THREAD

**Issue by skarampatakis** [openspending/openspending#1270] opened 2017-06-02 09:22 UTC
Hi @vitorbaptista,

In some cases. graphs contain multiple items as parts. It is really cool for the treemap or the bubble chart but when it comes to the pie chart or the radar chart, it renders hard to read and understand graphs. Take a look [here](http://eis-openbudgets.iais.fraunhofer.de/viewer/embed/piechart/budget-thessaloniki-revenue-2011__80bce?measure=%22amount.sum%22&groups%5B%5D=%22economicClassification.notation%22&filters%5BbudgetPhase.budgetPhase%5D%5B%5D=%22http:%2F%2Fdata.openbudgets.eu%2Fresource%2Fcodelist%2Fbudget-phase%2Fapproved%22&order=%22amount.sum%7Cdesc%22&lang=en)

![image](https://cloud.githubusercontent.com/assets/2419820/26711997/fd62fe90-476c-11e7-953a-4e3f549d53ad.png)

Would it be possible that we could limit the number of items shown? Ideally I think that we could show let say n = 5-8 slices with the top n values and aggregate the rest in a n+1 slice under the name "Other". Then if the user wants to see the composition of "Other" , clicks on the slice and gets the pie chart with the same limits as above and so on.   

As @pwalsh mentioned, there seems to be something like that here https://github.com/openspending/os-viewer/commit/2c1f3e810aac13647407fb67704fe44f76d7a0ea

I have not seen this in action yet but as stated here

> The slice that groups the smaller values can't be clicked on, as it makes no
sense to drill down in multiple categories.

From my point of view it makes sense to examine the composition of the aggregated slice, as there could be a user need to see what is hidden under the "Other" slice. Some times there might be dragons!

**Comment by vitorbaptista** [comment] 2017-06-07 18:59
@skarampatakis As you noticed, this was already fixed on that commit, we just need to deploy to production. Unfortunately, we found a bug on staging (#1274), which needs to be fixed before we can deploy the new release. I'm working on that, so it shouldn't take too long.

Regarding the drilldown behaviour, the problem is that it's a special case, which would require some time not only to develop the code, but also to think about the UI. I don't think it's worth it, as pie charts are notoriously bad for displaying many categories (some dataviz people even argue that pie charts should *never* be used). If there're many categories, the best option is to use a bar chart, which already has the correct drilldown behaviour.

Feel free to subscribe to #1274, as we should deploy a new version (with this behaviour fixed) after that's done.

I'm closing this issue for now. Please don't hesitate on reopening this issue (or creating another one) if you have more to talk.

**Closed by vitorbaptista** 2017-06-07 18:59 UTC
Labels: Docs, question

**Comment by skarampatakis** [comment] 2017-06-08 12:25
@vitorbaptista 

> If there're many categories, the best option is to use a bar chart, which already has the correct drilldown behaviour.

Can you point me to a dataset with the correct behavior? Is this on the production instance deployed or I should check latest update? I could find http://tinyurl.com/lloemst but it does not seems correct to me. Lower value bars are not even visible. Usually you aggregate the rest. And as I said if the user would like to see a more detailed view of the the "rest", you click and you get again the next top n + the rest aggregated if any. It is not an actual "drilldown" but I would say a refined view. 

> , but also to think about the UI

You won't change the UI. Just the graph. Perhaps a "Back" button to go to the previous view. Or the new view could be rendered under the primary view.

> I don't think it's worth it, as pie charts are notoriously bad for displaying many categories (some dataviz people even argue that pie charts should never be used).

I agree with you but pie charts are used pretty commonly and common people are familiar with them. So at least for our case we simply remove them. But I see this as an issue for other viz also (bar, bubble, radar). There are too many observations with little amounts that are totally lost on the vizs, but if you aggregate them, they are a big part of the whole budget.

**Comment by vitorbaptista** [comment] 2017-06-09 17:55
@skarampatakis 

> Can you point me to a dataset with the correct behavior? Is this on the production instance deployed or I should check latest update? I could find http://tinyurl.com/lloemst but it does not seems correct to me.

You're right, it's not possible to drilldown in the bar chart. This should be an easy fix, though. Just opened issue https://github.com/openspending/openspending/issues/1282 for it.

> Lower value bars are not even visible. Usually you aggregate the rest. And as I said if the user would like to see a more detailed view of the the "rest", you click and you get again the next top n + the rest aggregated if any. It is not an actual "drilldown" but I would say a refined view.

I think the solution here is to allow filtering, so people can enable/disable the rows as needed. A treemap is also an interesting alternative in this case, so at least you have an idea of how much of the total is contained in the long tail of small categories.

> You won't change the UI. Just the graph. Perhaps a "Back" button to go to the previous view. Or the new view could be rendered under the primary view.

By UI I mean the graph. We need to decide how this new behaviour would work, and how it fits in the big scheme.

> I agree with you but pie charts are used pretty commonly and common people are familiar with them. So at least for our case we can't simply remove them.

Definitely, that's why we have them. However, they have their limitations. Pie charts don't work when we have many categories. We can make them slightly better, but I think the correct solution is showing people the other options. We have other graphs that can display parts-to-a-whole, like the treemap and bubble tree, and the bar chart can also be used instead of a pie chart in many places. We should educate people to use pie charts only when they have few categories.

>  But I see this as an issue for other viz also (bar, bubble, radar). There are too many observations with little amounts that are totally lost on the vizs, but if you aggregate them, they are a big part of the whole budget.

Agreed. I commented about this issue above, quoting your phrase that starts with "Lower value bars are not even visible."
