### ISSUE TITLE
package status checking never finish for dataset named with "11th_test"

### ISSUE THREAD

**Issue by liyakun** [openspending/openspending#1357] opened 2018-05-10 11:13 UTC
I tried to upload a csv file through the openspending packager, but the upload process was stuck at the package status checking process like shown in the following figure even though the dataset and package file were already available. The file is available at [11th_test](https://openspending.org/viewer/5537104a902b0847bb7b474225eced5a:11th-test?lang=en).

![image](https://user-images.githubusercontent.com/7370334/39866898-c37254a8-5452-11e8-9bc4-872ed6bdd144.png)
 
This might be related with the code in [os-conductor/conductor/blueprints/package/controllers.py](https://github.com/openspending/os-conductor/blob/master/conductor/blueprints/package/controllers.py).

**Comment by badmotor** [comment] 2018-05-11 11:31
This issue seems to happen specifically when there is a "_" (underscore) character in the ID of the data package

**Comment by akariv** [comment] 2018-05-11 11:41
Thanks for reporting!

I will check this issue asap.

**Comment by brew** [comment] 2018-06-29 11:06
Closed as a duplicate of #1367.

**Closed by brew** 2018-06-29 11:06 UTC
