### ISSUE TITLE
OS Packager, mapping: design for the datatype selection dropdown

### ISSUE THREAD

**Issue by VictoriaVlad** [openspending/openspending#1056] opened 2016-07-25 19:31 UTC
Proposal to move the hover description to the side of the dropdown menu, since it currently hides the rest of menu. Example:
![hover](https://cloud.githubusercontent.com/assets/17012538/17114396/9aeef8ee-5263-11e6-9885-6d6234b2a8e6.png)

**Comment by akariv** [comment] 2016-07-26 05:06
The reason this position was chosen was b/c when on the right it would "fall off screen" for the rightmost column of cards.

**Comment by akariv** [comment] 2016-10-19 06:10
Assigned to Sam to see if he has any opinion on this.

**Comment by akariv** [comment] 2016-12-12 10:06
I changed the scope of this for a more holistic view of this dropdown.

**Comment by DianaMPG** [comment] 2017-01-31 08:09
estimate of 1 day to finish

**Comment by smth** [comment] 2017-03-28 14:18
My opinion is that those tooltips could be annoying. I suggest, as they are quite short, we just put them inline. To keep the lists fairly short, I'm also suggesting adding another level of navigation:

<img width="485" alt="image" src="https://cloud.githubusercontent.com/assets/1375708/24409508/552dfdc4-13c8-11e7-855d-604f00ae40fc.png">

Possibly more annoying would be not being able to go back up a level (without clearing the selection and starting again), so I've also added back arrows.

Live example on the third "column" [here](https://smth.github.io/os-mockup-packager/packager/describe-data/).

@akariv @DianaMPG

**Comment by akariv** [comment] 2017-03-29 19:18
Looks really good @smth, thanks!

@kravets-levko want to have a go at it?

**Comment by kravets-levko** [comment] 2017-03-29 20:06
It looks really good, I added a reaction :smile: 

@smth How about the second major issue - variable count of additional inputs (it depends on mapped data type)?

**Comment by kravets-levko** [comment] 2017-03-29 20:12
Sorry, probably my comment (above) shouldn't be here, but (I think) here we are talking about this selector in context of a new design of OS Packager, so It's also very important and blocks me from implementing it.

**Comment by DianaMPG** [comment] 2017-03-31 14:07
@smth I also like it very much, the suggested navigation gives better access to the mapping options.  
And I like the Back-arrow,  that is very helpful.

**Comment by DianaMPG** [comment] 2017-03-31 14:09
@smth and that one can switch off a column.

**Comment by smth** [comment] 2017-04-03 07:59
@kravets-levko some data types create additional fields, is that right? Which ones? Is there a limit on number of inputs?

**Comment by kravets-levko** [comment] 2017-04-03 18:59
@smth Yes, you're right. Currently additional fields are available for measures, date/time type and probably some others. But you should not rely on that - list of additional fields may be changed at any time.

**Comment by vitorbaptista** [comment] 2017-05-25 17:46
@akariv Looking the `osDatatype` code, I found that we're using [https://twitter.github.io/typeahead.js/](typeahead.js). However, it doesn't seem to be working (either locally or on production), at least not as a regular autocomplete field. It seems like this is as intended, and the autocomplete is simply used as a way to create the UI and filter the values as we click on each category. Is this correct?

I'm asking because it seems  @smth's design uses [http://mmenu.frebsite.nl](mmenu), which as far as I could see we don't. I could implement some of its features (namely going back a level) using typeahead, but I wonder if it isn't easier to use mmenu and reuse @smth's code. This will potentially make the code cleaner as well.

WDYT?

**Comment by pwalsh** [comment] 2017-06-02 09:54
@akariv ?

**Comment by akariv** [comment] 2017-06-05 12:17
Missed this one.

@vitorbaptista not hung up on typeahead at all - I used that as a convenience only.
If Sam's code uses a better lib, then let's use that.

**Comment by pwalsh** [comment] 2017-06-08 06:16
based on discussion with @smth I'm closing in favour of https://github.com/openspending/openspending/issues/1277

**Comment by vitorbaptista** [comment] 2017-06-08 20:10
Reopening, as I'm currently finishing this.

**Comment by vitorbaptista** [comment] 2017-06-12 17:50
We have a new design, so closing this as won't fix.

**Closed by vitorbaptista** 2017-06-12 17:50 UTC
Labels: in progress, Packager
