### ISSUE TITLE
Review OS-Viewer and make sure it’s not using babbage model

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1444] opened 2019-04-16 13:32 UTC
- Review Os-Viewer code
- List all locations that are using babbage model and not the fiscal data package
- Create sub-issues for modifying the code of Os-Viewer to remove dependency on babbage model completely

**Comment by akariv** [comment] 2019-04-17 08:06
There are 2 models coming from the API -
- one in the package (pre-v1 fdp model)
- one in the response itself (that's the babbage model, which also contains db related information)
- there are some pre-v1 attributes in the schema itself which we should ignore

Goal -
use just the FDPv1 schema + taxonomy to be able to access the API and show the UI

for now, we just want to do an analysis of what needs to be done, and then decide if we do
- in same code base
- in fork
- in fork + we need babbage modifications

Resources:
- FDP spec (read it to refresh on concepts and stuff)
- https://github.com/openspending/datapackage-pipelines-fiscal/tree/master/datapackage_pipelines_fiscal/processors - 
  - we have here code that takes the schema + model + taxonomy -> babbage model
  - we also have a wrapper around os-types
- https://github.com/openspending/os-types/tree/master/src
  - JS lib which takes taxonomy + schema -> pre-v1 fdp model
  - is also used internally by the packager

**Comment by nightsh** [comment] 2019-06-06 12:51
API is being hit three (relevant) times when loading a package:

1. `/search/package?id=<id>` to get a list of packages matching search criteria (which is only one, the ID, so it's gonna be a single element list)
  - this seems to be a hybrid FDP/Babbage model
  - Babbage model is assigned to the `model` key of the payload elements
  - FDP model is assigned to the `package` key of the same object
2. `/api/3/info/<id>/package` to get the pre-v1 FDP model
3. `/api/3/cubes/<id>/model` to get the Babbage model

As far as I can tell, the Babbage model is being used for getting the measures & dimensions (which cold also be found in the FDP model) and the FDP model is used to grab the metadata.

By comparing the two payloads, there are some things we cannot extract from the `package` object that are not in the `model` object:

- `model.dimensions`: 
  - each dimension has info on `join_column` which I believe it's only produced server side
- `fact_table`: I cannot easily see where this comes from

Rest of the Babbage model properties could be produced from the `package` object.

However, replacing the API-sourced babbage model with a client-side reproduction of it would only be good for backwards compatibility. In the long(er) term, we should update the directives etc. to use values straight from the FDP model.

We could do a branch, which could easily derive in a fork if it turns out to be too different from the original code base.

Overall, I would say these are the steps for the transition:

- remove all API requests for the babbage model
- here is a strategy branching point:
  - reconstruct the babbage model from the FDP model
    - see that the UI is still 100% functional using the emulated babbage model
    - refactor the UI bit by bit to read data straight from the FDP
  - **OR** keep the broken UI following the removal of the `model` from the payload
    - start rewiring the frontend to work with the `package` object and its structure
    - if not replaceable, add the missing babbage model properties through new API calls (involves amending the babbage API)
- rewrite all tests in the meantime

What I still don't have clear ideas for:

- method for getting cubes/dimensions members, how would it be impacted, if so

**Comment by nightsh** [comment] 2019-06-10 11:16
Further on, we need to make some alterations to babbage-ui:

- in `src/api/index.js`:
  - `getPackageModel()` requests the babbage model from `/api/3/cubes/<id>/model/`
  - this function is further chained to obtain various data from its result (e.g. measures, dimensions)
  - if we rewrite this to use a different data source (FDP model) but to keep its result structure, then it should be compatible with the rest of the codebase

---

In `os-viewer` we also need to:

- iterate over filtered FDP model dimensions in order to do a drill-down:
  - `os-viewer/params.js` does a `_.each(hierarchy.dimensions)` on the babbage model, but we can translate that to a filtered down `each()` on `package.model.dimensions` in the FDP model. Or to extract the dimensions aggregate into a separate function. This should be backwards compatible with everything.
  - `os-viewer/index.js` does a `map()` over babbage model hierarchies (`getHierarchiesWithLimitedDimensionValues()`), which we don't have in FDP model and would need to be reconstructed from the same `package.model.dimensions`, where we have keys like `package.model.dimensions.activity.attributes.activity2_code.parent`. This should be enough to provide us a tree.
    - this is used in `fullyPopulateModel()`, which could be left as it is, as the modification above is backwards compatible.
  - `loadDimensionsValues()` in `services/data-package-api` is requesting for each Dimension member a response from `/api/3/cubes/<package_id>/members/<dimension_id>/`
    - maybe we can leave this as is, for it doesn't duplicate the information in the FDP model
- maybe there is a way to pass the model from os-viewer to babbage-ui (and avoid extra requests made by babbage-ui). This way we won't have to also adapt babbage-ui anymore (see the beginning of this comment).

---

**Conclusions so far:**

1. Doing a backwards-compatible rewrite of os-viewer is doable, roughly keeping the functions that get data from the babbage model and replacing the logic inside them to extract information from the FDP model instead
2. The key `dimensions.fact_table` is needed for the package metadata, used to create dataMine URLs.
3. The `join_column` key in each dimension doesn't seem to be used anywhere in the code, either directly or indirectly. I removed it from the model and everything seems to be fine.
4. babbage-ui needs to adapt its package model retrieval, either by requesting an FDP model and reading from it, or directly receiving a pre-built model to work with.
5. I'd still do a branch instead of a fork, remove all the babbage model related lines and functions and start replacing them with FDP-sourced equivalents.

**Comment by nightsh** [comment] 2019-06-12 07:44
Where Babbage model is being used in os-viewer:

- module `services/data-package-api`
  - These functions use a FDP and a Babbage model, iterating over babbage model's top level attributes
    - `getMeasuresFromModel(dataPackage, model)`
    - `getDimensionsFromModel(dataPackage, model)`
    - `getHierarchiesFromModel(dataPackage, model)`
  - `createpackageModel(packageId, dataPackage, model)`
    This one creates a babbage model from the `/cubes/<id>/model/` API response
- `services/os-viewer/params`
  - `extractDrilldownLevels(params, packageModel)`
    This iterates over Babbage model's hierarchies' dimensions (constructed in `createPackageModel`)
  - similar to this there are multiple drilldown features using the same structure


Where Babbage model is being used in babbage.ui:

- `api/index`
  - calls the `/model` endpoint in its own `getPackageModel()`
  - uses `dimensions`, `aggregates`
  - uses the `column` field in `dimensions.attributes.<item>.column` in `getDimensionsFromModel(model)`



Babbage model data being explicitly used throughout the code:

- hierarchies
  - item
    - levels
    - label
- aggregates
  - item
    - measures
    - ref
    - label
- dimensions
  - dimension
    - key_ref
    - label
    - label_ref
    - hierarchy
    - key_attribute (babbage-ui)
    - label_attribute (babbage-ui)
    - attributes
      - item
        - column (babbage-ui)
- measures
  - ref
  - label

---

**NOTES:**
> There might be other pieces of code (in libs, for example) that could use other properties from the model. But as far as visulisations go, they all fetch cubes pieces and do not need the babbage model directly.

> Suggestion for implementation is to recreate a lightweight model and add non-obvious missing bits as needed (and maybe document them, so we'd have an overview of what I missed).

> The babbage model is used mainly as a glue throughout the app and could be replaced by the FDP model, which is now used more or less in the same way.

> We should be able to fetch the FDP model and recreate the needed bits out of it in a lighter data structure than what the babbage model is and with no additional API requests.
> We could compute the needed properties on demand straight from the FDP model, but given the overall reusability of the computed data in the code, that would be too intensive and it makes more sense to emulate a lighter babbage model.

**Comment by akariv** [comment] 2019-09-02 08:32
Once #1464 is closed this can be closed as well.

**Comment by akariv** [comment] 2019-09-02 08:34
Just to comment for anyone reviewing this in the future - 
we decided to tackle a more modest goal: instead of removing all references to babbage model from os-viewer, just to remove them from babbage.ui (and keep the fetching of the model in a single place in os-viewer)

**Closed** 2019-09-04 06:42 UTC
Labels: GIFT IV WP 3, Packager Refactor, os-viewer
