### ISSUE TITLE
Invalid sorting criterion in the url of the datasets in os-viewer

### ISSUE THREAD

**Issue by mlukasch** [openspending/openspending#1004] opened 2016-05-31 07:22 UTC
Some wrong sorting criterions show up in the url of the dataset in os-viewer (for example: "yznos.sum")
Investigation (& fixing if required) how those wrong criterions have been created would be helpful. 
There might be also other wrong criterions in the url besides the sorting criterion.

Such as:
http://next.openspending.org/viewer/583b10ad15f2e7f078afd3431c2c09ea:test?measure=adjusted.sum&order=yznos.sum|desc&groups[]=date_2.year&rows[]=date_2.year&columns[]=date_2.year

http://next.openspending.org/viewer/23cdc48554ae8648deff7837c025d8c0:pjcc16_test?measure=Amount.sum&order=yznos.sum|desc&visualizations[]=Treemap&groups[]=date_2.Year&rows[]=date_2.Year&columns[]=date_2.Year

http://next.openspending.org/viewer/1c95cb52b1d32ee8537fafd2fe1a945d:ekondo?measure=Depenses_realisees.sum&order=yznos.sum|desc&groups[]=date_2.Annee&rows[]=date_2.Annee&columns[]=date_2.Annee

The urls show up with the following setup:
master-branch in os-viewer
feature/modern-branch in babbage.ui

This issue is related to:
https://github.com/openspending/openspending/issues/967

**Comment by mlukasch** [comment] 2016-05-31 07:28
![osviewer_url](https://cloud.githubusercontent.com/assets/17597578/15666607/fa090400-2711-11e6-93ba-e83e38d704db.PNG)

**Comment by akariv** [comment] 2016-05-31 11:16
I think this is a duplicate of #971

**Closed** 2016-06-06 10:51 UTC
