### ISSUE TITLE
Can't get to step 4: 404 and Illegal Invocation

### ISSUE THREAD

**Issue by stevage** [openspending/openspending#876] opened 2016-02-29 12:41 UTC
I was testing out the Data Packager locally. The first couple of steps go fine, but as soon as I enter a "name" for the data package, the app stops doing anything further. In the console there is this:

```
modules.js?14567490368597852:16 GET http://localhost:5000/proxy?url=https%3A%2F%2Frawgit.com%2Fdataprotocols%2Fregistry%2Fmaster%2Fregistry.csv 404 (Not Found)(anonymous function) @ modules.js?14567490368597852:16t._execute @ modules.js?14567490368597852:2i._resolveFromExecutor @ modules.js?14567490368597852:3i @ modules.js?14567490368597852:2r @ modules.js?14567490368597852:16i @ modules.js?14567490368597852:16(anonymous function) @ modules.js?14567490368597852:1t._execute @ modules.js?14567490368597852:2i._resolveFromExecutor @ modules.js?14567490368597852:3i @ modules.js?14567490368597852:2i.loadSchema @ modules.js?14567490368597852:1i.validateFiscalDataPackage @ modules.js?14567490368597852:1(anonymous function) @ validation.js:44A @ vendor.js?14567490368597852:201A @ vendor.js?14567490368597852:201validateFiscalDataPackage @ validation.js:43e.validatePackage @ provide-metadata.js:69fn @ VM929:4r.$eval @ vendor.js?14567490368597852:212pre @ vendor.js?14567490368597852:336ea @ vendor.js?14567490368597852:152D @ vendor.js?14567490368597852:141g @ vendor.js?14567490368597852:134(anonymous function) @ vendor.js?14567490368597852:133(anonymous function) @ vendor.js?14567490368597852:135k @ vendor.js?14567490368597852:139(anonymous function) @ vendor.js?14567490368597852:333r.$digest @ vendor.js?14567490368597852:210r.$apply @ vendor.js?14567490368597852:213$$debounceViewValueCommit @ vendor.js?14567490368597852:344$setViewValue @ vendor.js?14567490368597852:344k @ vendor.js?14567490368597852:242Q.event.dispatch @ modules.js?14567490368597852:39g.handle @ modules.js?14567490368597852:38
2016-02-29 23:38:14.346 vendor.js?14567490368597852:186 TypeError: Illegal invocation
    at Object.t.defaultErrorHandler (env.js:5)
    at validation.js:59
    at vendor.js?14567490368597852:198
    at r.$eval (vendor.js?14567490368597852:212)
    at r.$digest (vendor.js?14567490368597852:209)
    at vendor.js?14567490368597852:212
    at e (vendor.js?14567490368597852:122)
    at vendor.js?14567490368597852:125
```

It seems to be trying to access https://rawgit.com/dataprotocols/registry/master/registry.csv, which doesn't exist.

Filling out the rest of the fields briefly shows a "validating data package" message, before the same two errors appear again in the log, and no further progress seems to be possible.

Sorry if this isn't helpful. Is it expected that I could generate a datapackage.json from it? (I'm not looking to publish the actual dataset anywhere.)

**Comment by akariv** [comment] 2016-03-04 15:38
@stevage can you please make sure you're using the latest master branch? 
I can see that this URL was changed to `http://schemas.datapackages.org/registry.csv` about 2 months ago.

**Comment by stevage** [comment] 2016-03-08 05:57
Yep, the latest commit was:

```
commit 3bfcc421c47a43a621916cf96cb653ec5073a9b0
Author: Paul Walsh <paulywalsh@gmail.com>
Date:   Wed Feb 24 09:48:37 2016 +0200
```

**Comment by akariv** [comment] 2016-03-08 06:28
Yes, it indeed looks like a rebuild issue.

**Comment by pwalsh** [comment] 2016-03-20 09:54
@stevage I'm closing this. Please re-open if the issue is elsewhere.

**Closed by pwalsh** 2016-03-20 09:54 UTC
