### ISSUE TITLE
Viewer filtering cause bad API calls

### ISSUE THREAD

**Issue by akariv** [openspending/openspending#1274] opened 2017-06-05 13:13 UTC
@vitorbaptista 
compare:

https://next.openspending.org/viewer/6018ab87076187018fc29c94a68a3cd2:presupuesto-mexico-2008-2017?measure=%22MONTO_MODIFICADO.sum%22&groups%5B%5D=%22administrative_classification_2.ID_RAMO%22&filters%5Bdate_2.CICLO%5D%5B%5D=2017&order=%22MONTO_MODIFICADO.sum%7Cdesc%22&visualizations%5B%5D=%22PieChart%22&lang=en

vs

https://staging.openspending.org/viewer/6018ab87076187018fc29c94a68a3cd2:presupuesto-mexico-2008-2017?measure="MONTO_MODIFICADO.sum"&groups%5B%5D="administrative_classification_2.ID_RAMO"&filters%5Bdate_2.CICLO%5D%5B%5D=2017&order="MONTO_MODIFICADO.sum%7Cdesc"&visualizations%5B%5D="PieChart"&lang=en

(only difference is `next` vs `staging`).

On staging all API calls get 400 responses.

Compare:
next API call:
https://next.openspending.org/api/3/cubes/6018ab87076187018fc29c94a68a3cd2:presupuesto-mexico-2008-2017/members/functional_classification_ID_3?cut=date_2.CICLO%3A2017
staging API call:
https://staging.openspending.org/api/3/cubes/6018ab87076187018fc29c94a68a3cd2%3Apresupuesto-mexico-2008-2017/members/functional_classification_ID_3?cut=date_2.CICLO%253A2017

I guess this happened in one of the last modifications (the Sankey fix perhaps?)

**Comment by vitorbaptista** [comment] 2017-06-07 18:49
I couldn't reproduce this locally. However, there was another issue while running `os-viewer` locally (see #1280). Maybe that's related. Let's re-check this after that's merged.

**Closed** 2017-06-15 16:51 UTC
Labels: bug, in progress, Viewer
