### ISSUE TITLE
OS Viewer: add user location in hierarchical dataset structure

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#908] opened 2016-03-30 00:46 UTC
The user needs to know their location in the dataset's hierarchical structure in order to possibly browse back and forth to a higher/lower level in the hierarchy.

It will allow the user to keep track of its navigation and better control it. 
Works a bit like a sort of breadcrumb trail. 

This description is updated as the user changes the measures and dimensions on the control panel. 

<img width="745" alt="capture d ecran 2016-03-30 a 01 34 33" src="https://cloud.githubusercontent.com/assets/6681719/14128446/f35af912-f618-11e5-923a-74ec61698587.png">

**Comment by pwalsh** [comment] 2016-03-30 06:05
I agree this is really important, and while this information **is** indicated in the side bar, adding it in a similar way to your description is a great idea.

I'd say this should not be assigned to anyone except Sam though, unless you think this is absolutely critical to do this week.

@smth WDYT?

**Comment by akariv** [comment] 2016-03-30 06:42
Just to add some information, in the new left panel implementation it's not going to appear (as it's not something the user will generally want to touch).
Perhaps this is another thing that should be part of the generic nav control.

**Comment by smth** [comment] 2016-03-30 07:09
This is specific to a single chart, or relevant to the whole page?

**Comment by cecilaki** [comment] 2016-03-30 07:12
@smth to a single chart actually. 
Good question. Was wondering where the metadata description of the whole file was supposed to be displayed, if the information exists. I would assume below the main title?

**Comment by smth** [comment] 2016-03-30 07:22
So this relates to, and could be a part of the description here with https://github.com/openspending/openspending/issues/909

**Comment by cecilaki** [comment] 2016-03-30 07:35
Sure, but then, placed above the viz? 
(and give more space to the viz in the container at the same time)
I think it should be editable also so the user can change it if s/he wants to customize the description. 

So 
1 - Implementing this description pulling out the available info:
- Measure / phase if available
- Date/time/year 
- Direction?
- Currency? 
- Group by
- Hierarchy position (not sure how to indicate the hierarchical level though) 
- Other?

2 - Make it editable

<img width="794" alt="capture d ecran 2016-03-30 a 01 56 05" src="https://cloud.githubusercontent.com/assets/6681719/14134724/f93964c6-f650-11e5-9d5c-7dae084f361f.png">

**Comment by smth** [comment] 2016-03-30 07:43
Do the visulisations need more (horizontal) space? I was limiting their width slightly, so in the event we have a square visualisation, it wouldn't take up the whole screen.

I guess your primary reason for moving the description is concern that it doesn't have enough space. Is that right?

**Comment by pwalsh** [comment] 2016-03-30 07:46
I like the text and controls where they are. it is a more flexible design for vis of different width and height dimensions, and, especially as we develop the embed versions, leaves good space for a consistent "toolkit" for controlling the vis, utilising vertical space well.

**Comment by cecilaki** [comment] 2016-03-30 08:06
@smth not necessarily no. It's not a concern since I think the viz is currently well proportioned and has enough space. I actually like the current design and implementation as well :) 

And  +1 to leaving some space for more viz controls in the right  

Originally I was thinking more of a 'breadcrumb'-like indication to help user locating in the dataset and displaying a human language to what s/he's visualising. Hence have that above the viz as a reference. 

The impact would be slightly different if this info is located on the right bottom corner of the viz cause the use would probably need to scroll down a little bit. But we can try and see how that would work in practice.

I really think it's a crucial info to display though.

**Comment by cecilaki** [comment] 2016-04-21 09:38
Reiterating the first objective as Spec:

Add a title "Currently Viewing" below the "Views" (or to replace the "Views") to describe the visualisation being displayed on top, specifying variables, year displayed and situate the user in the hierarchies on the datasets (as long as those hierarchies are identifies as such) 

This title does not belong to the Viz Embed container.

Objective: Situate the user in the dataset's hierarchical structure, in order to possibly browse back and forth to a higher/lower level in the hierarchy and indicate clearly what s/he is looking at, in which dimension(s) s/he is navigating into. 

Idea is to have a sort of a breadcrumb trail made of data pulled out of the control panel and phrased the way a human can read it. 

This description is updated as the user changes the measures and dimensions on the control panel.

**Comment by smth** [comment] 2016-04-26 14:54
I have a few questions @cecilaki 

- Why do we need "Currently Viewing"? Doesn't the relationship between the title and the visualisation make that clear?
- What is "Views"? (It's not in my mockup)
- Could you clarify "This title does not belong to the Viz Embed container" please? My understanding is that we are talking about the title and description to the right of each visualisation, and that those titles and descriptions relate to their respective visualisations.
- I'm not sure what we are talking about in regards to a hierarchy. Does this refer to being able to drill down within a treemap?

**Comment by cecilaki** [comment] 2016-04-26 15:23
- _Why do we need "Currently Viewing"? Doesn't the relationship between the title and the visualisation make that clear?_

Unfortunately not. The Title is the dataset title but doesn't reflect the visualisations being produced. 
When the users are creating different viz types and playing with the different measures and dimensions, they're lost in the different levels of hierarchies and which dimension they selected. 

The viz becomes meaningless and they loose interest in less than 5 sec.

- _What is "Views"? (It's not in my mockup)_

Don't know. @akariv ?

- _Could you clarify "This title does not belong to the Viz Embed container" please? My understanding is that we are talking about the title and description to the right of each visualisation (#909), and that those titles and descriptions relate to their respective visualisations._

Yes. This title/breacrumb I want to implement is a human phrasing of the visualisation currently being displayed. 
It is not the visualisation title on the left. (which is described in the #909 ) 
It is not static and is changing as the user is selecting measures or dimensions, or is navigating through the viz. Ideally I'd like to display in a simple phrase (could be a breadcrumb style too actually if a sentence is too complicated ) the selected options from the left panel + the levels of hierarchies in which the user is navigating . 

Which is the reason why this title/breadcrumb should not belong to the "embedded container" ( don't know how to call it) Cause it is a navigation indicator more than a description of the viz that the user wants to share once the viz is finalized. 

- I'm not sure what we are talking about in regards to a hierarchy. Does this refer to being able to drill down within a treemap?

We are talking about the different levels of hierarchies that we can find a dataset. 
Example: 
Level 1 > Government / List of all Ministries  
Level 2 > Ministry of Education / List of all administrative departments in this ministry
Level 3 > Department of Primary schools / 

And yes, we should be able to drill down in and out those hierarchies in a treemap and a bubble tree.

**Comment by akariv** [comment] 2016-04-26 16:46
> What is "Views"? (It's not in my mockup)

@smth Just a title - we can ignore that.

> Which is the reason why this title/breadcrumb should not belong to the "embedded container" ( don't know how to call it) Cause it is a navigation indicator more than a description of the viz that the user wants to share once the viz is finalized.

The problem is how the user is supposed to navigate between the hierarchies of the vis without this navigation control when the treemap is embedded.

The way I see it, this is a reusable component, which might appear either in the main OS-Viewer UI (above all visualizations) or in the embedded view.

**Comment by cecilaki** [comment] 2016-04-26 17:08
I always thought the user would navigate between these hierarchies by clicking on them, like in this [bubble tree WDMMG style](http://danfowler.github.io/bubbletree/demos/macedonia/index.html#/~/total). There is no navigation control, it's an embedded viz, and we can navigate through it. 

I'm all in favor of adding the nav control though, especially a "back" button, but at least, the treemaps and bubble tree viz should allow the above navigation.

So +1 for this reusable component, but also +1 on navigating in the viz by zooming in directly into it. 

Also, do we agree on showing the active filters displayed above the viz as a navigation indicator?

**Comment by akariv** [comment] 2016-04-26 17:11
@cecilaki not sure I understand where the user should click on a treemap (or pie chart) in order to back up to the parent level.

**Comment by cecilaki** [comment] 2016-04-26 17:25
@akariv well, true, without a back button, s/he can't. (I think..) 

What I don't understand is:
- it's currently possible to zoom in the [treemap](http://next.openspending.org/viewer/8c248ff162c3c3b957f487138850eaf2:kisela-voda-bubble-viz?measure=yznos.sum&order=yznos.sum%7Casc&visualizations%5B%5D=Treemap&groups%5B%5D=classification_economic_stavka_opys.stavka_opys&rows%5B%5D=classification_economic_bylans.bylans&columns%5B%5D=classification_economic_bylans.bylans&filters=classification_economic_bylans.bylans%7C%D1%80%D0%B0%D1%81%D1%85%D0%BE%D0%B4%D0%B8) ( as per @victoria's latest upload and test) 
- it's also possible to zoom out with the navigation control arrows that are currently on the top right outside and above the viz.

What we we miss is: 
- Those controls to be integrated **inside** the viz to they're part of the embed as well
( what does it take to do that?)
- Some simple text saying "back" or "navigation" to indicate what are those buttons for

Something else?

**Comment by akariv** [comment] 2016-04-26 17:42
That's the thing - I'm don't think that these controls should be integrated
within each viz, but rather as an external component.

**Comment by cecilaki** [comment] 2016-04-26 17:46
Oh yes, sorry I didn't express myself correctly. By "integrated inside the viz", I meant, **in the embed container** (how can we call that to have a common reference?) 

So that would be an external component placed in the embed with the viz so both can be shared. 
(but as it is right now, no? Aren't the existing navigation button external components?)

Hope it's more clear.

**Comment by smth** [comment] 2016-04-27 06:24
> Unfortunately not. The Title is the dataset title but doesn't reflect the visualisations being produced.

You see this as the dataset title?
![title](https://cloud.githubusercontent.com/assets/1375708/14843365/83b15260-0c47-11e6-8392-47cf73cf8cee.png)

> Cause it is a navigation indicator more than a description of the viz that the user wants to share once the viz is finalized.

So the distinction here is that it only needs to be present in OS Viewer, and shouldn't be part of the shared/embedded version?

> We are talking about the different levels of hierarchies that we can find a dataset. 

If this answer was "yes", I'd be happy that we are on the same page (a breadcrumb for a treemap or bubbletree makes absolute sense). As it is, I'm still slightly concerned that I am missing something. Is it possible for me to see a working example of what you'd like to navigate here?

**Comment by cecilaki** [comment] 2016-04-27 08:02
@smth I was thinking about something like that: 

1. Display the selected measures or dimensions 
2. Display the hierarchies as breadcrumb

By the way, in this example, the viz below represents exactly what's in the breadcrumb and description. 
It's so much easier to navigate not only back and forth in the viz, but also to change settings from the left panel and try other dimensions or measures. 

![viewer_treemap_breadcrumb](https://cloud.githubusercontent.com/assets/6681719/14845036/90e4d874-0c53-11e6-8b93-cecb8713a192.png)

Then we can discuss whether it makes more sense to add this breadcrumb in the `vis embedded mode` so it replaces the navigation buttons to move back and forth in the drilldown if viz embedded.  

![viewer_treemap_breadcrumb_embedded_mode](https://cloud.githubusercontent.com/assets/6681719/14845546/c01af490-0c56-11e6-99fc-a09aa3102bf7.png)

WDYT? cc @akariv

**Comment by smth** [comment] 2016-04-27 08:30
I'm not sold on the value of repeating what is selected in the left column, but willing to be persuaded.

The breadcrumb, I think we are on the same page. It should be in context with the treemap I believe. (If there's a concern that it shouldn't be present when embeded, I'm sure there'll be a way to omit it in that scenario.)

**Comment by smth** [comment] 2016-04-27 12:49
New elements incorporated here:
![viewer_03_charts_02](https://cloud.githubusercontent.com/assets/1375708/14852526/bffcda14-0c7e-11e6-9abf-166079f07d69.jpg)

**Comment by cecilaki** [comment] 2016-04-27 12:57
@smth wow BRILLIANT ! that addresses **exactly** all needs IMHO

**Comment by cecilaki** [comment] 2016-04-27 13:00
@smth one question: Is the `< />` icon in black near the main dataset title in the page, for embedding the whole app without header and footer?

**Comment by smth** [comment] 2016-04-27 13:02
Yes, for sharing the whole page, as read only, in some fashion (if we need it).

**Comment by cecilaki** [comment] 2016-04-27 13:07
We definitely need it. It's even ready if I understood correctly. Look [here](http://os-viewer.herokuapp.com/embed/405f5e1681d4b6673fbfc0ceb196fe47:boost-armenia-2006-2014?measure=adjusted.sum&visualizations%5B%5D=Treemap&visualizations%5B%5D=BubbleTree&groups%5B%5D=classification_economic_econ1.econ1&rows%5B%5D=activity.program&columns%5B%5D=activity.program).  

Is that how you envisioned the `read-only`mode @akariv ?

**Closed** 2016-05-07 06:59 UTC
Labels: enhancement, UX, Viewer
