### ISSUE TITLE
Unable to publish a CSV file as a FDP

### ISSUE THREAD

**Issue by cecilaki** [openspending/openspending#859] opened 2016-02-16 17:15 UTC
When tried to published this CSV > [Budget of Balakovo_2016_v.2.csv.zip](https://github.com/openspending/openspending/files/132936/Budget.of.Balakovo_2016_v.2.csv.zip)

I got this error : 
<img width="1170" alt="capture d ecran 2016-02-16 a 16 59 39" src="https://cloud.githubusercontent.com/assets/6681719/13083940/7a94deba-d4d7-11e5-8c52-16dede9a6a01.png">

Before publication I've made the following mappings/settings: 
**Defined Amount**
Column:  amount
**Defined Classification Administrative**
Columns:  level1_title +  level2_title
**Defined Activity**
Column: level3_title
**Defined Datetime**
Column: budget_date

**Comment by akariv** [comment] 2016-02-17 07:50
@cecilaki 
This error is caused by the fact that your original filename contained spaces.

I opened an issue that should resolve this problem:
https://github.com/datapackages/datapackage-py/issues/35

**Comment by cecilaki** [comment] 2016-02-17 08:12
Allright, great! So spaces in filenames should be allowed when this is resolved. 
Just tried publishing again without spaces in file name but I still get an error.
<img width="1176" alt="capture d ecran 2016-02-17 a 09 10 44" src="https://cloud.githubusercontent.com/assets/6681719/13103395/81c92432-d556-11e5-9847-853dee480c69.png">

**Comment by akariv** [comment] 2016-02-17 11:57
On to the next issue then :)

I retried reproducing this issue - the problem was that the CSV file uses semicolons instead of commas... 

@pwalsh is this allowed by the spec? weren't we supposed to detect this with GoodTables?

**Comment by pwalsh** [comment] 2016-02-17 12:02
semi-colons should be allowed as a delimiter. I'm not sure what GoodTables did in this case, and we should raise an issue about that *anyway*. But I guess here, the error occurs in the later parsing of the file in order to read into the DB, in which case I'd suggest [we sniff for the delimiter](https://docs.python.org/3/library/csv.html#csv.Sniffer).

**Comment by akariv** [comment] 2016-02-17 13:14
I guess this is another issue for tabulator.

**Comment by roll** [comment] 2016-02-18 15:21
All `csv` settings like `delimiter` of `sniffer class` could be passed to tabulator. Which one it's a responsibility of higher level layers in my opinion.

**Comment by pwalsh** [comment] 2016-02-18 15:29
@roll ok, what is the API for passing this data in?

**Comment by roll** [comment] 2016-02-18 15:34
@pwalsh
```
table = topen('path.csv',
        parser_options={'delimeter': ';', dialect: SniffingDialect()},
        parser_class=parsers.CSV,  # by default
)
```

**Comment by rgrp** [comment] 2016-02-18 15:34
@pwalsh / @roll are we supporting CSV Dialect Description Format stuff - http://dataprotocols.org/csv-dialect/ (this would also maintain clear separation from the sniffer - the sniffer should produce CSV DDF). Again, IME it is often better simply to let the user tell you this than try and guess - just give them options on the first loader page to set key options - delimiter, quotechar etc (perhaps hide by default or make clear defaults are probably fine).

**Comment by roll** [comment] 2016-02-18 15:50
@rgrp `tabulator` doesn't use it for now

About guessing/sniffing:

http://dataprotocols.org/tabular-data-package

> CSV files generated by different applications often vary in their syntax, e.g. use of quoting characters, delimiters, etc. To encourage conformance, CSV files in a Tabular Data Package SHOULD
> 
> - Use “,” as field delimiters
> - Use “\r\n” or “\n” as line terminators
>
> **If a CSV file does not follow these rules then its specific CSV dialect MUST be documented. The resource hash for the resource in the datapackage.json descriptor MUST**:
> 
> - Include a dialect key that conforms to that described in the CSV Dialect Description Format
> - Applications processing the CSV file SHOULD use the dialect of the CSV file to guide parsing.

I think it means some higher level should understand [CSV Dialect Description Format (CSVDDF)] (http://dataprotocols.org/csv-dialect/) and pass corresponding csv options to `tabulator`.

**Comment by akariv** [comment] 2016-02-22 08:39
Okay, I opened these:
https://github.com/openspending/os-packager/issues/66
https://github.com/datapackages/datapackage-py/issues/52
https://github.com/datapackages/tabulator-py/issues/47

**Comment by akariv** [comment] 2016-02-26 20:08
duplicate of #866

**Closed by akariv** 2016-02-26 20:08 UTC
Labels: bug, Packager
