### ISSUE TITLE
Validation error: Invalid type: string (expected number) at /model/measures/amount/factor (Packager)

### ISSUE THREAD

**Issue by stevage** [openspending/openspending#945] opened 2016-04-16 10:50 UTC
No matter what (numeric value) I put in the "Factor" box, I get this message on the "Name your data package" screen. 
```
{
  "message": "Invalid type: string (expected number)",
  "params": {
    "type": "string",
    "expected": "number"
  },
  "code": 0,
  "dataPath": "/model/measures/amount/factor",
  "schemaPath": "/properties/model/properties/measures/patternProperties/^\\w+/properties/factor/type",
  "subErrors": null,
  "type": "schema"
}
```

I can't progress beyond it.

**Comment by akariv** [comment] 2016-04-16 11:11
Hey, this is a duplicate of #869.

**Comment by stevage** [comment] 2016-04-16 11:21
Hmm, not exactly. I'm entering a number, but getting that error anyway.

**Comment by akariv** [comment] 2016-04-16 16:13
Yes, that's the 2nd bullet there - anything you type is interpreted as a
string, thus not confirming the schema which requires a number there
instead.

**Closed** 2016-04-17 06:32 UTC
